# Generated by Django 2.2.6 on 2019-10-24 21:51

from django.db import migrations
import django_enumfield.db.fields
import like.models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_type',
            field=django_enumfield.db.fields.EnumField(default=0, enum=like.models.LikeType),
        ),
    ]
