# Generated by Django 2.2.6 on 2019-10-24 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_like_like_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='book_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_like', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='like',
            name='game_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_like', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='like',
            name='track_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_like', to='tracks.Track'),
        ),
    ]
